// src/components/Layout/Header.jsx
import React, { useState } from "react";
import { Icon } from "@iconify/react";
import { useNavigate } from "react-router-dom";
import {
  Button,
  Menu,
  MenuItem,
  Avatar,
  IconButton,
  Drawer,
  List,
  ListItem,
  ListItemButton,
  ListItemText,
  Box
} from "@mui/material";
import { useAuth } from "../../contexts/AuthContext";
// import DrawerList from "./DrawerList"; // You can create a separate file or keep it internal

const navLinks = [
  { name: "Sākums", path: "/", icon: "material-symbols:home-outline" },
  { name: "Spēlēt", path: "/play", icon: "fa6-solid:chess-knight" },
  { name: "Mācīties", path: "/training", icon: "material-symbols:school-outline" },
  { name: "Analīze", path: "/analysis", icon: "material-symbols:analytics-outline" },
];

const Header = () => {
  const navigate = useNavigate();
  const { user, logout } = useAuth();
  const [anchorEl, setAnchorEl] = useState(null);
  const [mobileOpen, setMobileOpen] = useState(false);

  const handleMenuOpen = (event) => setAnchorEl(event.currentTarget);
  const handleMenuClose = () => setAnchorEl(null);
  
  const handleLogout = () => {
    logout();
    handleMenuClose();
    navigate("/");
  };

  const DrawerList = () => (
    <Box sx={{ width: 250, bgcolor: '#262421', height: '100%', color: 'white' }} role="presentation" onClick={() => setMobileOpen(false)}>
      <List>
        {navLinks.map((link) => (
          <ListItem key={link.name} disablePadding>
            <ListItemButton onClick={() => navigate(link.path)}>
              <Icon icon={link.icon} width="24" height="24" className="mr-4 text-[#2C75FF]" />
              <ListItemText primary={link.name} />
            </ListItemButton>
          </ListItem>
        ))}
      </List>
    </Box>
  );

  return (
    <header className="fixed w-full top-0 z-50 bg-[#302E2B]/80 backdrop-blur-md border-b border-white/10 shadow-lg transition-all duration-300">
      <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-20">
          
          {/* LOGO */}
          <div 
            className="flex items-center gap-2 cursor-pointer" 
            onClick={() => navigate("/")}
          >
             <Icon icon="fa6-solid:chess" className="text-[#2C75FF] text-3xl" />
             <span className="text-xl font-bold tracking-wider text-white">
               CHESS<span className="text-[#2C75FF]">MASTER</span>
             </span>
          </div>

          {/* DESKTOP NAV */}
          <div className="hidden md:flex space-x-8 items-center">
            {navLinks.map((link) => (
              <a
                key={link.name}
                onClick={() => navigate(link.path)}
                className="text-gray-300 hover:text-[#2C75FF] transition-colors cursor-pointer text-sm font-medium uppercase tracking-wide flex items-center gap-2"
              >
                <Icon icon={link.icon} width="20" />
                {link.name}
              </a>
            ))}
          </div>

          {/* AUTH ACTIONS */}
          <div className="flex items-center gap-4">
            {user ? (
              <>
                <IconButton onClick={handleMenuOpen} sx={{ p: 0 }}>
                  <Avatar sx={{ bgcolor: '#2C75FF' }}>
                    {user.name ? user.name[0] : 'U'}
                  </Avatar>
                </IconButton>
                <Menu
                  anchorEl={anchorEl}
                  open={Boolean(anchorEl)}
                  onClose={handleMenuClose}
                  PaperProps={{
                    style: { backgroundColor: '#262421', color: 'white', border: '1px solid #444' }
                  }}
                >
                  <MenuItem onClick={() => navigate("/dashboard")}>Vadības Panelis</MenuItem>
                  <MenuItem onClick={handleLogout} sx={{ color: '#ff6b6b' }}>Iziet</MenuItem>
                </Menu>
              </>
            ) : (
              <Button
                variant="contained"
                onClick={() => navigate("/login")}
                sx={{
                  backgroundColor: '#2C75FF',
                  animation: "slideDown 0.8s",
                  '&:hover': { backgroundColor: '#1a60e0' }
                }}
              >
                Pieslēgties
              </Button>
            )}

            {/* MOBILE MENU TOGGLE */}
            <div className="md:hidden">
              <IconButton onClick={() => setMobileOpen(true)} sx={{ color: 'white' }}>
                <Icon icon="material-symbols:menu" width="32" />
              </IconButton>
            </div>
          </div>
        </div>
      </nav>

      <Drawer anchor="right" open={mobileOpen} onClose={() => setMobileOpen(false)}>
        <DrawerList />
      </Drawer>

      <style>{`
        @keyframes slideDown {
          from { transform: translateY(-30px); opacity: 0; }
          to { transform: translateY(0); opacity: 1; }
        }
      `}</style>
    </header>
  );
};

export default Header;

// resources/js/components/Header.vue
<script setup>
import { ref } from 'vue';
import { useAuthStore } from '../stores/auth';
const auth = useAuthStore();
const mobileOpen = ref(false);

const navLinks = [
    { to: '/', label: 'Panelis', icon: '◈' },
    { to: '/games', label: 'Partijas', icon: '♟' },
    { to: '/play', label: 'Spēlēt', icon: '♚' },
    { to: '/openings', label: 'Atklātnes', icon: '📖' },
    { to: '/lessons', label: 'Mācības', icon: '🎓' },
    { to: '/training', label: 'Treniņi', icon: '⚡' },
];
</script>

<template>
    <header class="sticky top-0 z-50 backdrop-blur-xl bg-[#0c0c0e]/90 border-b border-white/5">
        <nav class="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
            <router-link to="/" class="flex items-center gap-3 group">
                <div class="w-10 h-10 bg-gradient-to-br from-amber-400 to-amber-600 rounded-xl flex items-center justify-center shadow-lg shadow-amber-500/20 group-hover:shadow-amber-500/40 transition-shadow">
                    <svg class="w-6 h-6 text-black" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 2L9 7H6l-3 5h4l-2 4h3l-3 6h6l-1-3h4l-1 3h6l-3-6h3l-2-4h4L18 7h-3L12 2zm0 3.5L13.5 8h-3L12 5.5z"/>
                    </svg>
                </div>
                <div>
                    <span class="text-lg font-black tracking-tight text-white">ŠAHA</span>
                    <span class="text-lg font-light tracking-tight text-amber-400 ml-1">ANALĪZE</span>
                </div>
            </router-link>

            <div class="hidden md:flex items-center gap-1" v-if="auth.isLoggedIn">
                <router-link v-for="link in navLinks" :key="link.to" :to="link.to"
                    class="px-4 py-2 rounded-xl text-sm font-semibold text-zinc-400 hover:text-amber-400 hover:bg-white/5 transition-all"
                    active-class="!text-amber-400 !bg-amber-400/10">
                    <span class="mr-1.5">{{ link.icon }}</span>{{ link.label }}
                </router-link>

                <router-link v-if="auth.isAdmin" to="/admin"
                    class="px-4 py-2 rounded-xl text-sm font-semibold text-zinc-400 hover:text-amber-400 hover:bg-white/5 transition-all"
                    active-class="!text-amber-400 !bg-amber-400/10">
                    <span class="mr-1.5">⚙</span>Admin
                </router-link>
            </div>

            <div class="hidden md:flex items-center gap-4" v-if="auth.isLoggedIn">
                <router-link to="/profile" class="text-right group cursor-pointer">
                    <p class="text-xs font-bold text-zinc-400 group-hover:text-amber-400 transition-colors">{{ auth.user?.name }}</p>
                    <p class="text-[10px] text-zinc-600 uppercase tracking-wider">ELO {{ auth.user?.elo_rating }}</p>
                </router-link>
                <router-link to="/logout"
                    class="px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-wider text-zinc-500 border border-zinc-800 hover:border-red-900 hover:text-red-400 transition-all">
                    Iziet
                </router-link>
            </div>

            <button @click="mobileOpen = !mobileOpen" class="md:hidden p-2 text-zinc-400" v-if="auth.isLoggedIn">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
                </svg>
            </button>
        </nav>

        <div v-if="mobileOpen && auth.isLoggedIn" class="md:hidden border-t border-white/5 px-6 py-4 flex flex-col gap-2">
            <router-link v-for="link in [...navLinks, {to:'/profile',label:'Profils'}, ...(auth.isAdmin ? [{to:'/admin',label:'Admin'}] : []), {to:'/logout',label:'Iziet'}]"
                :key="link.to" :to="link.to" @click="mobileOpen = false"
                class="py-2 text-sm font-semibold text-zinc-400 hover:text-amber-400 transition-colors">
                {{ link.label }}
            </router-link>
        </div>
    </header>
</template>
